### ISSUE TITLE
setup Protocol

### ISSUE THREAD

**Issue by Nashorn** [DcmanProductions/UAUP-JS#2]
How can I add support for BitBucket private repo?

```
function setupGitProtocol(options) {
    options.gitRepo = options.gitRepo.toString().replace('/ /gi', '-');
    git_api = `https://api.github.com/repos/${options.gitUsername}/${options.gitRepo}/releases/latest`;
}
```

**Comment by Drew-Chase** [comment]
Bit Bucket has a REST API, which you would use instead of the git api.  Although if Bit Bucket uses different naming scheme you would have to rewrite most of the variables, because most of my variables use git specific keywords.

**Comment by Drew-Chase** [comment]
bit bucket reset api documentation can be found here -> https://developer.atlassian.com/server/bitbucket/reference/rest-api/
