### ISSUE TITLE
getting 404 error

### ISSUE THREAD

**Issue by zerqs** [DcmanProductions/UAUP-JS#3]
F:\electron app\node_modules\uaup-js\index.js:150 GET https://api.github.com/repos/zerqs/passwordManager/releases/latest 404
GetUpdateVersion @ F:\electron app\node_modules\uaup-js\index.js:150
CheckForUpdates @ F:\electron app\node_modules\uaup-js\index.js:265
F:\electron app\node_modules\uaup-js\index.js:274 Couln't find the Version File, this usually means that there was no previous update.
CheckForUpdates @ F:\electron app\node_modules\uaup-js\index.js:274
async function (async)
CheckForUpdates @ F:\electron app\node_modules\uaup-js\index.js:265
F:\electron app\node_modules\uaup-js\index.js:210 Update Found!
F:\electron app\node_modules\uaup-js\index.js:128 GET https://api.github.com/repos/zerqs/passwordManager/releases/latest 404
GetUpdateURL @ F:\electron app\node_modules\uaup-js\index.js:128
Update @ F:\electron app\node_modules\uaup-js\index.js:233
async function (async)
Update @ F:\electron app\node_modules\uaup-js\index.js:232
F:\electron app\node_modules\uaup-js\index.js:139 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at F:\electron app\node_modules\uaup-js\index.js:139
    at async Object.Update (F:\electron app\node_modules\uaup-js\index.js:233)
(anonymous) @ F:\electron app\node_modules\uaup-js\index.js:139
async function (async)
Update @ F:\electron app\node_modules\uaup-js\index.js:232

**Comment by Drew-Chase** [comment]
The given repository doesn't exist.  So the auto updater can't get information from a repository that doesn't exist
