### ISSUE TITLE
Code signing certificate

### ISSUE THREAD

**Issue by PeterKottas** [DcmanProductions/UAUP-JS#4]
This seems quite interesting, however, I do have a question before diving in deeper. Everywhere I looked, the electron apps require code signing using a certificate which is especially painful on Mac, as the certificates there are relatively pricey. I wonder how come this is not mentioned/necessary here. Can you please explain? I think many people will be asking this. Cheers!

**Comment by Drew-Chase** [comment]
Code signing is definitely a pain (especially regarding IOS).  Adding support for certificates is beyond the scope of this project.  It will be up to the individual developer to include (or don't include) their own code signing implementation.
This project will not bypass the need or requirement for code signed certs and on platforms that require them, one will need to be obtained from a authorized retailer.
